 import java.awt.image.BufferedImage;
 
 
 public class T_common
   extends Tiles
 {
   private static final byte ID = 1;
   private final BufferedImage image;
   
   T_common(boolean isAutoGenerated, short x, short y) {
     super(isAutoGenerated);
     if (isAutoGenerated) {
       this.image = Controle.tile1;
     } else {
       this.image = Controle.tile2;
     }  this.Xpos = x;
     this.Ypos = y;
   }
   
   protected byte getID() {
     return 1;
   }
   
   protected BufferedImage getImage() {
     return this.image;
   }
   
   protected String getArgs() {
     if (this.isAutoGenerated)
       return null; 
     return String.valueOf(this.Xpos) + "," + this.Ypos + "/";
   }
   
   protected void main() {}
 }
