 import java.awt.Rectangle;
 import java.awt.image.BufferedImage;
 
 
 public class T_killing
   extends Tiles
 {
   private static final byte ID = 2;
   private final BufferedImage image;
   
   T_killing(boolean isAutoGenerated, short x, short y) {
     super(isAutoGenerated);
     if (isAutoGenerated) {
       this.image = Controle.tile1;
     } else {
       this.image = Controle.killingBlock;
     }  this.Xpos = x;
     this.Ypos = y;
   }
   
   protected BufferedImage getImage() {
     return this.image;
   }
   
   protected byte getID() {
     return 2;
   }
   
   protected boolean intersection(boolean Player, int x, int y, int width, int height) {
     boolean intersects = (new Rectangle(this.Xpos, this.Ypos, 50, 50)).intersects(new Rectangle(x, y, width, height));
     if (Player && intersects)
       AnimationSpecific.dieAnimation(); 
     return intersects;
   }
   
   protected String getArgs() {
     if (this.isAutoGenerated)
       return null; 
     return String.valueOf(this.Xpos) + "," + this.Ypos + "/";
   }
   
   protected void main() {}
 }