 import java.awt.image.BufferedImage;
 
 public class T_vanishing
   extends Tiles
 {
   private static final byte ID = 3;
   private static final BufferedImage image = Controle.vanishingBlock;
   private final short stayTime;
   private final short awayTime;
   
   T_vanishing(boolean isAutoGenerated, short x, short y, short stayTime, short awayTime) {
     super(isAutoGenerated);
     this.Xpos = x;
     this.temX = x;
     this.Ypos = y;
     this.stayTime = stayTime;
     this.awayTime = awayTime;
   }
   private final short temX; private short stateTime; private boolean away;
   protected BufferedImage getImage() {
     return image;
   }
   
   protected byte getID() {
     return 3;
   }
   
   protected String getArgs() {
     if (this.isAutoGenerated)
       return null; 
     return String.valueOf(this.temX) + "," + this.Ypos + "," + this.stayTime + "," + this.awayTime + "/";
   }
   
   protected short[] realPos() {
     return new short[] { this.temX, this.Ypos };
   }
 
 
 
   
   protected void main() {
     this.stateTime = (short)(this.stateTime - 1);
     if (this.stateTime <= 0) {
       this.away = !this.away;
       if (this.away) {
         this.stateTime = this.awayTime;
         this.Xpos = -1000;
       } else {
         
         this.stateTime = this.stayTime;
         this.Xpos = this.temX;
       } 
     } 
   }
 }
